[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pwd-manager"
version = "1.0.0"
description = "A web-based secure password manager."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "Flask==3.1.2",
    "Werkzeug==3.1.4",
    "Flask-SQLAlchemy==3.0.2",
    "Flask-Migrate==4.0.5",
    "Flask-Bcrypt==1.0.1",
    "python-dotenv==1.0.0",
    "cryptography==46.0.3",
    "gunicorn==23.0.0",
    "qrcode==8.2",
    "Pillow==12.0.0",
    "markdown==3.7",
    "click>=8.1.0",
]

[project.scripts]
start = "pwd_manager.cli:start"
stop = "pwd_manager.cli:stop"

[tool.hatch.build.targets.wheel]
packages = ["src/pwd_manager"]

[tool.uv]
dev-dependencies = ["pytest>=9.0.1"]
