"""Add notes field to SecretEntry

Revision ID: 363da605ac29
Revises: 
Create Date: 2025-12-03 20:45:54.598211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363da605ac29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('password_entry')]
    
    if 'notes' not in columns:
        with op.batch_alter_table('password_entry', schema=None) as batch_op:
            batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_entry', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
