"""Drop legacy encryption_key column

Revision ID: 42e5886d4023
Revises: 59c9ce8a53e7
Create Date: 2026-07-30 22:31:21.824167

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42e5886d4023'
down_revision = '59c9ce8a53e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('kdf_salt',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('kdf_iterations',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wrapped_dek',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('encryption_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('wrapped_dek',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('kdf_iterations',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('kdf_salt',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
