"""Add key wrapping columns

Revision ID: 59c9ce8a53e7
Revises: add_document_tags
Create Date: 2026-07-30 22:14:59.129611

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '59c9ce8a53e7'
down_revision = 'add_document_tags'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kdf_salt', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('kdf_iterations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wrapped_dek', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('key_version', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('encryption_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('encryption_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('key_version')
        batch_op.drop_column('wrapped_dek')
        batch_op.drop_column('kdf_iterations')
        batch_op.drop_column('kdf_salt')

    # ### end Alembic commands ###
