"""make document collection_id not null

Revision ID: 7b0c18b8befb
Revises: c1ba8f7a0d57
Create Date: 2026-07-31 16:13:13.316557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0c18b8befb'
down_revision = 'c1ba8f7a0d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
