"""add collection support

Revision ID: c1ba8f7a0d57
Revises: 42e5886d4023
Create Date: 2026-07-31 14:31:10.522146

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c1ba8f7a0d57'
down_revision = '42e5886d4023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_document_collection', 'collection', ['collection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('fk_document_collection', type_='foreignkey')
        batch_op.drop_column('collection_id')

    # ### end Alembic commands ###
